server:
  port: 18888
  servlet:
    context-path: /fds

spring:
  application:
    name: fast-api-service
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #设置返回json数据null字段不显示
    default-property-inclusion: non_null
  profiles:
    active: dev




