server:
  port: 18888

spring:
  application:
    name: fast-api-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.10.0.10:3306/fast_api?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    host: 10.10.0.10
    port: 6379
  main:
    allow-circular-references: true

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher



#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.shepherd.fast.entity
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    global-config:
      db-config:
        id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
        #      id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
        #      id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
        #      id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


multilevel:
  cache:

    #    maxCapacityRate: 0.2
    #    initRate: 0.5
    name: multilevel-cache
    topic: multilevel-cache-topic
    #    redisName: multilevel-redis-cache
    #    caffeineName: multilevel-caffeine-cache
    caffeine-expire-time: 60
    redis-expire-time: 120
    redis-name: multilevel-redis-cache
    caffeine-name: multilevel-caffeine-cache
    caffeine-switch: true
    max-capacity: 256
    init-capacity: 32

swagger-info:
  title: fast-api
  description: 快速生成接口
  version: 1.0.0
  base-package: com.plasticene.fast.controller
  url: http://www.shepherd126.top/
  author: shepherd
  email: shepherd_zfj163.com

ptc:
  trace:
    enable: true
  tenant:
    enable: false
  encrypt:
    algorithm: aes

  api:
    security:
      enable: true
      rsa-public-key: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArd+hCsqwEjddzpNEOmMKUjLiK4uqUhx3o7qyV7iEKIVrdcnDQHLlO0juQX+xeselFqpqe9m25xH8TO3VmZCo7RkdwxsFTuk7vvObb3/STsWPry9X1jYxilw8/ui9TcBAgY2HwkfxhO3WqEzCKDs0EI0Z+16F0P7KeGSyTgL5FoPyYvFQgMQSygqsaPe3055RCr4vhOvyfhbe1tw5X/TU5l90j3eebMzN9r6m3dCG+CmA7Gr/GRytRtzXx68Rc75Z7jkWsEMk5fentMsjaJ4hP2heqK21bI9Z7dvtNG4ZTFVO05pJXecru2eSHU9KXfOCT2e/6h5vEoLibTdd99smEJRBEnfuIfMkLAtndbWq3vQkVe+d7Z+uof3CasJrYO0MYkpcxPmZzlUbrdPRKnc3FI/J8R1toWnsDiN8MKbHj+jd6ojfk/HqIsQJcj+SWGmYS/Dh3j/XngFdFu9yWprC2bJgdVt9w5hskHi9cpaWn2BXj7DQ5SvNR9RULS3qMs8HLaTQdATMfX0FiMZl4AIsIwQv1aiHOTuw/HVc0KECSwy14YH3pY33Iu2waGBrOjmbwVYikgoOK8TCeDzC0SvWu7PRpPpwIwjppEJZVf/u/sR64+n2UGtsVT4Xk5CtlVNyyz2bQ7I6QxcThtdv86+vrVcSwhJrApr1h8aHg5pncPcCAwEAAQ==
      rsa-private-key: MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCt36EKyrASN13Ok0Q6YwpSMuIri6pSHHejurJXuIQohWt1ycNAcuU7SO5Bf7F6x6UWqmp72bbnEfxM7dWZkKjtGR3DGwVO6Tu+85tvf9JOxY+vL1fWNjGKXDz+6L1NwECBjYfCR/GE7daoTMIoOzQQjRn7XoXQ/sp4ZLJOAvkWg/Ji8VCAxBLKCqxo97fTnlEKvi+E6/J+Ft7W3Dlf9NTmX3SPd55szM32vqbd0Ib4KYDsav8ZHK1G3NfHrxFzvlnuORawQyTl96e0yyNoniE/aF6orbVsj1nt2+00bhlMVU7Tmkld5yu7Z5IdT0pd84JPZ7/qHm8SguJtN1332yYQlEESd+4h8yQsC2d1tare9CRV753tn66h/cJqwmtg7QxiSlzE+ZnOVRut09EqdzcUj8nxHW2haewOI3wwpseP6N3qiN+T8eoixAlyP5JYaZhL8OHeP9eeAV0W73JamsLZsmB1W33DmGyQeL1ylpafYFePsNDlK81H1FQtLeoyzwctpNB0BMx9fQWIxmXgAiwjBC/VqIc5O7D8dVzQoQJLDLXhgfeljfci7bBoYGs6OZvBViKSCg4rxMJ4PMLRK9a7s9Gk+nAjCOmkQllV/+7+xHrj6fZQa2xVPheTkK2VU3LLPZtDsjpDFxOG12/zr6+tVxLCEmsCmvWHxoeDmmdw9wIDAQABAoICACGRtHjt6xKJR/4zJpATQRHfqxT3MRoLTvn4eKhBApsEL1wdaSoPRLyudvmEWtK2quP2YPqqbQqtyUVdAclVSZgFKl7Z36t9kkBqrg7X4dW9hOEwxcegzO3Goywf6TSSsqGQnq5ez313oeL6dt3nmES9yU9jz3grSRH3dwliv46eSPTbXEyQDoSdjO3zLbWYslLdpzUFjNrVNY7ME/O3xEb6FPoCAT9GR1mlM3hN41EUSkTa34eMptOwnaR642ayUJCSyxOa0wvnRaS9N4fiR88DKotshkOAZb9rn59oxk+bhM2L0zBjCmlzNJ2eCmCbPARypnXgDFfJl0e40daho/Zqlqg04zxHleJSqyeWVaay/oaYjKBQrMn/Gf7Zr+KVTdVRfelxFX3BS+Ex75bd+meSAxoyFeBXzYnPsvErgw8aZGxFML49qwewJvXyvif7uNCbKHI6cXBLbrXPnhCIg99PI5lDCY66WRiA3PPGqMjcFjvb+wuWMGkhPfXDLawZy02h+6PztspYh0CWD9Sc/k+ANZwnw+x3c8EQnqJXwdp6oY8Wz7YJ+0aHO3JrjbcckXhsBEmM2rJxAI8Sx1OyKFfrhahTlLZ6BBzBVpyOyFiVx37HdmPdy3izzhGa8dlTOW8Ma7E3nIFYBESO4sDYefKnrIMVtwJ2jIiQeC2jSOthAoIBAQD+L5T29KBnhZSyB+d+yxvb8Dc8rk91kz8Y3s5gnayEGQ8vzmuVrP8LXoqveYIqUquFIZVGQbRhqMPNj8cp3we9ya2sbNwk/7OfxrcraVCAzNpr2VVTcv8GnoqoC9DFcBChpgfUKyb02W6JljuwNXchRAo8tRtSVBG+3Zs1YONbocMG1c64fOtY8lN41Xd+ae/O7zh6cgKGHzgtHBdVyzQ7OLYv0EL/yUOgsyWPXAMURApANb2ymC0RW6o8+INsRDUcHcF69ZpzwQ1P+3mNWG16M1Cr3utSJXU1LgfCAH2SVm40eR/jDsMsbA6wMY0kJY9LJcqgrH03vvkUCwRtPeVHAoIBAQCvHU9iHIEvUPD3nv+/mXllLuNV8ZAYzmN7qSkawLr2H5nEzoHgF6UWb9wmfcyle/W1chI2D1Q0G9hXfIJyCfarFBpaQKy0bds4HZ9i+8GlFMJEfbZ9KYw/NeTJ8TU65t6c0aV/qIXwrw5j/F6ft3+XkhiUMvFrVB5wcj2J1htSob2f6nYMYb0Bv7T7p7PIWQrf2XEbOYauHpLOevk4Wsth3cOfYoHHtrGBMHS1qX5wX2dXDxdzErVyDRKZq2EKSict9OskFprRRvaJFxxVWrZ5hUCYHzfa/q0QXMgEv3+vvG+xXuJ+OdM5D/piyAGZ6J67ZcI1WUZVDO/p40E3L67RAoIBAQCvTQWBY6iUfK3WMllXOqCWCI8vzE+EmO51KoROYa+u0tGEeOn9qfejUap35mb85VLhWA3pDDto9slDJZuHpwdhvouGVPVmluq8kIGW8OTST3V718Fe8fosCH878hojcGwn76eKjdAqISJ4xSGZHuZwDMq6n3SeTNiIN7FpGM70TRWBy0bsOUreZxFmTmJAzrLSlmzvFV3kPfeyNKNrSd9V0IDlbM4oNhfr5mFLA3wkJ+Ch8+5GE2lRhVRdBE8vBcNTBrp/II9KsaOKu7ZS4t9t3aIPRogoeSjiakJza38uw2jxy29QWsgEBOoEXcgnW7f9bazXLt6U6aJCTm7ZIEzVAoIBAHqshssNevaBtn1R1ooL4v4eLcYsVqz6ELk1lQUX1SHMm3VC0bsB9XXVYR1Z7X5Ua5nz0owqiuuCQjlvkRaAolvQ1nE5c4NmnjcekWTPRyX1d+5xPuFJtOUnRSKvJoIf7/1d5JmcnlAw4lzrFALBktHE2BEh6vwsTrKpZTDlW/i0M9oObypXYggSm5/cKNcGgda1RkYzM4VRB7k8btCq0mW57GwAnzggZRNCtc/5cAka3JMhkGTdy1ydidU7ONzze6T3Oa7rYwOOufDpzsCArupMjibDX+a7mNOom7qvyKx8zqYr+XFB4xXLerWutWhzjJdtPvMOmnXEfWGVAT++2LECggEBAPDZ7bWejBAwc5B8p1FypxPhgyYkGqEAR1rMgxe6DLeZOaT8tW7TF4dK6+4giBLswiUn6Jr5b6H1Z+a/7EmueI0ojcP4LFZgX08E8UrmDxZiRdglndOl1J2weORTd902DdhalyCcuiYboYMjCtezZ+tBilgrhv2dUv1JsUuAQ3JOFW1QBJLj6LpRotAsCoe0mllMYe/5K8QRxRXVfsIbtXFNvZ/x9AxG8YSAVtyXM7345L/GFW2xRIjzia3JwaLuUCrn3Pa33HeAZ5lyGYJ2USywchftP3vahobFJKXi4RU5atmLeBiC/97iA4TNehvbw7wyokZmEYMKJDPHfeeui0Y=
      valid-time: 600000
    log:
      enable: true
#  license:
#    license-path: /Users/shepherdmy/Desktop/license/license.lic
#    private-keys-store-path: /Users/shepherdmy/Desktop/license/privateKeys.keystore
#    public-keys-store-path: /Users/shepherdmy/Desktop/license/publicCerts.keystore
#    verify-system-switch: false
#    key-pass: 12345
#    store-pass: 12345
#    start-check: false
